openapi: 3.0.0
info:
  title: Meter User Assignment API
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MeterUserAssignment:
      type: object
      properties:
        meterId:
          type: string
        userId:
          type: integer
    Meter:
      type: object
      properties:
        meterId:
          type: string
        name:
          type: string
        productName:
          type: string
        description:
          type: string
        location:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Profile:
      type: object
      properties:
        userId:
          type: integer
        name:
          type: string
        email:
          type: string
        userRole:
          type: string
    MetersResponse:
      type: object
      properties:
        meters:
          type: array
          items:
            $ref: '#/components/schemas/Meter'
        total:
          type: integer
    UsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/Profile'
        total:
          type: integer
paths:
  /meter-user/assign:
    post:
      summary: Assign a meter to a user
      description: Assigns a meter to a user. If the meter is already assigned to another user, the operation will be rejected.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterUserAssignment'
      responses:
        '200':
          description: Assignment successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '403':
          description: Meter has already been assigned to another user
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /meter-user/unassign:
    post:
      summary: Unassign a meter from a user
      description: Removes the assignment of a meter from a user.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterUserAssignment'
      responses:
        '200':
          description: Unassignment successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '404':
          description: Meter was not assigned to this user
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /meter-user/user/{userId}/meters:
    get:
      summary: Get meters assigned to a user
      description: Retrieves all meters that are assigned to a specific user.
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of meters assigned to the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetersResponse'

  /meter-user/meter/{meterId}/users:
    get:
      summary: Get users assigned to a meter
      description: Retrieves all users assigned to a specific meter. Since a meter can only be assigned to one user, this will return either a list with one user or an empty list.
      security:
        - bearerAuth: []
      parameters:
        - name: meterId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of users assigned to the meter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'

  /meter-user/is-assigned:
    get:
      summary: Check if a meter is assigned to a user
      description: Checks if a specific meter is assigned to a specific user.
      security:
        - bearerAuth: []
      parameters:
        - name: meterId
          in: query
          required: true
          schema:
            type: string
        - name: userId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Assignment status
          content:
            application/json:
              schema:
                type: object
                properties:
                  isAssigned:
                    type: boolean

  /meter-user/meters/unassigned:
    get:
      summary: Get all meters not assigned to any user
      description: Retrieves all meters that are not currently assigned to any user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of unassigned meters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetersResponse'

  /meter-user/meter/{meterId}/user:
    get:
      summary: Get the user assigned to a specific meter
      description: Retrieves the user that is assigned to a specific meter, if any.
      security:
        - bearerAuth: []
      parameters:
        - name: meterId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The user assigned to the meter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: No user is assigned to this meter
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /meter-user/meter/{meterId}/users-without:
    get:
      summary: Get users not assigned to a specific meter
      description: Retrieves all users that are not assigned to a specific meter.
      security:
        - bearerAuth: []
      parameters:
        - name: meterId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of users not assigned to the meter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'
