ktor:
  application:
    modules:
      - com.mike.ApplicationKt.module

  development: true

  deployment:
    port: ${PORT}
    host: ${HOST}
    watch:
      - classes
      - resources

# Security configuration for authentication
security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    realm: ${JWT_REALM}
    token_expiration: ${JWT_TOKEN_EXPIRATION}

database:
  driver: ${DATABASE_DRIVER}
  url: ${DATABASE_URL}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
